# Generated by Django 6.0.3 on 2026-04-04 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_email', models.EmailField(max_length=254)),
                ('email_type', models.CharField(choices=[('confirmation', 'Confirmation'), ('status_update', 'Status Update'), ('assignment', 'Assignment')], max_length=15)),
                ('sendgrid_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='sent', max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'email_logs',
                'ordering': ['-sent_at'],
            },
        ),
    ]
